version: '3.9'

services:
  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    depends_on:
      - database

  database:
    container_name: ${PROJECT_NAME}-db
    image: mariadb:10.3
    volumes:
      - ./configs/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - ${LOCAL_DB_PORT}:3306
    restart: always
    environment:
      - MYSQL_PASSWORD=${LOCAL_USER_PASSWORD}
      - MYSQL_USER=${LOCAL_USER_LOGIN}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
      - MARIADB_ROOT_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  database:
